language: rust
rust:
  - nightly
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - rustup component add rustfmt clippy
  - cargo fmt --all -- --check
  - cargo clippy
